server:
  port: 8222

spring:
  application:
    name: API-GATEWAY 

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/students/**
        - id: collage-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/collage/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
